
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AsideMenu': typeof import("../src/components/AsideMenu.vue")['default']
    'AsideMenuItem': typeof import("../src/components/AsideMenuItem.vue")['default']
    'AsideMenuLayer': typeof import("../src/components/AsideMenuLayer.vue")['default']
    'AsideMenuList': typeof import("../src/components/AsideMenuList.vue")['default']
    'BaseDivider': typeof import("../src/components/BaseDivider.vue")['default']
    'BaseIcon': typeof import("../src/components/BaseIcon.vue")['default']
    'BaseLevel': typeof import("../src/components/BaseLevel.vue")['default']
    'CardBox': typeof import("../src/components/CardBox.vue")['default']
    'CardBoxComponentBody': typeof import("../src/components/CardBoxComponentBody.vue")['default']
    'CardBoxComponentFooter': typeof import("../src/components/CardBoxComponentFooter.vue")['default']
    'CardBoxMenu': typeof import("../src/components/CardBoxMenu.vue")['default']
    'CardBoxMenuMaterial': typeof import("../src/components/CardBoxMenuMaterial.vue")['default']
    'FooterBar': typeof import("../src/components/FooterBar.vue")['default']
    'FormsAdmisiDataDiriMhs': typeof import("../src/components/Forms/Admisi/DataDiriMhs.vue")['default']
    'FormsAdmisiDataOrangTuaWali': typeof import("../src/components/Forms/Admisi/DataOrangTuaWali.vue")['default']
    'FormsAdmisiInformasiKontak': typeof import("../src/components/Forms/Admisi/InformasiKontak.vue")['default']
    'FormsAdmisiPendataanDifabel': typeof import("../src/components/Forms/Admisi/PendataanDifabel.vue")['default']
    'FormsAdmisiPersonalInformation': typeof import("../src/components/Forms/Admisi/PersonalInformation.vue")['default']
    'FormsAdmisiRiwayatPendidikan': typeof import("../src/components/Forms/Admisi/RiwayatPendidikan.vue")['default']
    'FormsAdmisiUnggahBerkas': typeof import("../src/components/Forms/Admisi/UnggahBerkas.vue")['default']
    'FormsAdmisiUploadFiles': typeof import("../src/components/Forms/Admisi/UploadFiles.vue")['default']
    'ModalHistoyApproval': typeof import("../src/components/Modal/HistoyApproval.vue")['default']
    'ModalLoginAsMhs': typeof import("../src/components/Modal/LoginAsMhs.vue")['default']
    'ModalLoginAsPengembang': typeof import("../src/components/Modal/LoginAsPengembang.vue")['default']
    'ModalUploadFileTtd': typeof import("../src/components/Modal/ModalUploadFileTtd.vue")['default']
    'ModalProsesValidasiDitolak': typeof import("../src/components/Modal/ProsesValidasi/Ditolak.vue")['default']
    'ModalProsesValidasiSubmit': typeof import("../src/components/Modal/ProsesValidasi/Submit.vue")['default']
    'ModalUbahPassword': typeof import("../src/components/Modal/UbahPassword.vue")['default']
    'ModalUbahRole': typeof import("../src/components/Modal/UbahRole.vue")['default']
    'ModalUploadSertifikat': typeof import("../src/components/Modal/UploadSertifikat.vue")['default']
    'NavBar': typeof import("../src/components/NavBar.vue")['default']
    'NavBarItem': typeof import("../src/components/NavBarItem.vue")['default']
    'NavBarItemPlain': typeof import("../src/components/NavBarItemPlain.vue")['default']
    'NavBarMenuList': typeof import("../src/components/NavBarMenuList.vue")['default']
    'OverlayLayer': typeof import("../src/components/OverlayLayer.vue")['default']
    'SectionFullScreen': typeof import("../src/components/SectionFullScreen.vue")['default']
    'SectionMain': typeof import("../src/components/SectionMain.vue")['default']
    'SelectCustom': typeof import("../src/components/Select_custom.vue")['default']
    'TableDataTable': typeof import("../src/components/Table/DataTable.vue")['default']
    'TableTabulator': typeof import("../src/components/TableTabulator.vue")['default']
    'UserAvatar': typeof import("../src/components/UserAvatar.vue")['default']
    'UserAvatarCurrentUser': typeof import("../src/components/UserAvatarCurrentUser.vue")['default']
    'UtilsFormsCKEditor': typeof import("../src/components/Utils/Forms/CKEditor.vue")['default']
    'UtilsFormsCKEditor2': typeof import("../src/components/Utils/Forms/CKEditor2.vue")['default']
    'UtilsFormsDatePicker': typeof import("../src/components/Utils/Forms/DatePicker.vue")['default']
    'UtilsFormsQuillEditor': typeof import("../src/components/Utils/Forms/QuillEditor.vue")['default']
    'UtilsFormsTextEditor': typeof import("../src/components/Utils/Forms/TextEditor.vue")['default']
    'UtilsFormsTextEditorTipTap': typeof import("../src/components/Utils/Forms/TextEditorTipTap.vue")['default']
    'UtilsFormsTinyMCE': typeof import("../src/components/Utils/Forms/TinyMCE.vue")['default']
    'UtilsSkeletonsQalender': typeof import("../src/components/Utils/Skeletons/Qalender.vue")['default']
    'UAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'UAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'UAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'UAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'UBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'UButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'UButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'UCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'UChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'UDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'UIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'UKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'ULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'UMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'UMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'UProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'UCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'UForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'UFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'UInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'UInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'URadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'URadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'URange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'USelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'USelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'UTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'UToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'UTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'UCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'UContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'UDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'USkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'UBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'UCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'UCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'UHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'UPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'UTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'UVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'UContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'UModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'UNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'UNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'UPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'USlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'UTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'NuxtTurnstile': typeof import("../node_modules/@nuxtjs/turnstile/dist/runtime/components/NuxtTurnstile.vue")['default']
    'UnoIcon': typeof import("../node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'TiptapEditorContent': typeof import("@tiptap/vue-3")['EditorContent']
    'TiptapFloatingMenu': typeof import("@tiptap/vue-3")['FloatingMenu']
    'TiptapBubbleMenu': typeof import("@tiptap/vue-3")['BubbleMenu']
    'VDatePicker': typeof import("v-calendar")['DatePicker']
    'VCalendar': typeof import("v-calendar")['Calendar']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAsideMenu': typeof import("../src/components/AsideMenu.vue")['default']
    'LazyAsideMenuItem': typeof import("../src/components/AsideMenuItem.vue")['default']
    'LazyAsideMenuLayer': typeof import("../src/components/AsideMenuLayer.vue")['default']
    'LazyAsideMenuList': typeof import("../src/components/AsideMenuList.vue")['default']
    'LazyBaseDivider': typeof import("../src/components/BaseDivider.vue")['default']
    'LazyBaseIcon': typeof import("../src/components/BaseIcon.vue")['default']
    'LazyBaseLevel': typeof import("../src/components/BaseLevel.vue")['default']
    'LazyCardBox': typeof import("../src/components/CardBox.vue")['default']
    'LazyCardBoxComponentBody': typeof import("../src/components/CardBoxComponentBody.vue")['default']
    'LazyCardBoxComponentFooter': typeof import("../src/components/CardBoxComponentFooter.vue")['default']
    'LazyCardBoxMenu': typeof import("../src/components/CardBoxMenu.vue")['default']
    'LazyCardBoxMenuMaterial': typeof import("../src/components/CardBoxMenuMaterial.vue")['default']
    'LazyFooterBar': typeof import("../src/components/FooterBar.vue")['default']
    'LazyFormsAdmisiDataDiriMhs': typeof import("../src/components/Forms/Admisi/DataDiriMhs.vue")['default']
    'LazyFormsAdmisiDataOrangTuaWali': typeof import("../src/components/Forms/Admisi/DataOrangTuaWali.vue")['default']
    'LazyFormsAdmisiInformasiKontak': typeof import("../src/components/Forms/Admisi/InformasiKontak.vue")['default']
    'LazyFormsAdmisiPendataanDifabel': typeof import("../src/components/Forms/Admisi/PendataanDifabel.vue")['default']
    'LazyFormsAdmisiPersonalInformation': typeof import("../src/components/Forms/Admisi/PersonalInformation.vue")['default']
    'LazyFormsAdmisiRiwayatPendidikan': typeof import("../src/components/Forms/Admisi/RiwayatPendidikan.vue")['default']
    'LazyFormsAdmisiUnggahBerkas': typeof import("../src/components/Forms/Admisi/UnggahBerkas.vue")['default']
    'LazyFormsAdmisiUploadFiles': typeof import("../src/components/Forms/Admisi/UploadFiles.vue")['default']
    'LazyModalHistoyApproval': typeof import("../src/components/Modal/HistoyApproval.vue")['default']
    'LazyModalLoginAsMhs': typeof import("../src/components/Modal/LoginAsMhs.vue")['default']
    'LazyModalLoginAsPengembang': typeof import("../src/components/Modal/LoginAsPengembang.vue")['default']
    'LazyModalUploadFileTtd': typeof import("../src/components/Modal/ModalUploadFileTtd.vue")['default']
    'LazyModalProsesValidasiDitolak': typeof import("../src/components/Modal/ProsesValidasi/Ditolak.vue")['default']
    'LazyModalProsesValidasiSubmit': typeof import("../src/components/Modal/ProsesValidasi/Submit.vue")['default']
    'LazyModalUbahPassword': typeof import("../src/components/Modal/UbahPassword.vue")['default']
    'LazyModalUbahRole': typeof import("../src/components/Modal/UbahRole.vue")['default']
    'LazyModalUploadSertifikat': typeof import("../src/components/Modal/UploadSertifikat.vue")['default']
    'LazyNavBar': typeof import("../src/components/NavBar.vue")['default']
    'LazyNavBarItem': typeof import("../src/components/NavBarItem.vue")['default']
    'LazyNavBarItemPlain': typeof import("../src/components/NavBarItemPlain.vue")['default']
    'LazyNavBarMenuList': typeof import("../src/components/NavBarMenuList.vue")['default']
    'LazyOverlayLayer': typeof import("../src/components/OverlayLayer.vue")['default']
    'LazySectionFullScreen': typeof import("../src/components/SectionFullScreen.vue")['default']
    'LazySectionMain': typeof import("../src/components/SectionMain.vue")['default']
    'LazySelectCustom': typeof import("../src/components/Select_custom.vue")['default']
    'LazyTableDataTable': typeof import("../src/components/Table/DataTable.vue")['default']
    'LazyTableTabulator': typeof import("../src/components/TableTabulator.vue")['default']
    'LazyUserAvatar': typeof import("../src/components/UserAvatar.vue")['default']
    'LazyUserAvatarCurrentUser': typeof import("../src/components/UserAvatarCurrentUser.vue")['default']
    'LazyUtilsFormsCKEditor': typeof import("../src/components/Utils/Forms/CKEditor.vue")['default']
    'LazyUtilsFormsCKEditor2': typeof import("../src/components/Utils/Forms/CKEditor2.vue")['default']
    'LazyUtilsFormsDatePicker': typeof import("../src/components/Utils/Forms/DatePicker.vue")['default']
    'LazyUtilsFormsQuillEditor': typeof import("../src/components/Utils/Forms/QuillEditor.vue")['default']
    'LazyUtilsFormsTextEditor': typeof import("../src/components/Utils/Forms/TextEditor.vue")['default']
    'LazyUtilsFormsTextEditorTipTap': typeof import("../src/components/Utils/Forms/TextEditorTipTap.vue")['default']
    'LazyUtilsFormsTinyMCE': typeof import("../src/components/Utils/Forms/TinyMCE.vue")['default']
    'LazyUtilsSkeletonsQalender': typeof import("../src/components/Utils/Skeletons/Qalender.vue")['default']
    'LazyUAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'LazyUAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'LazyUAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'LazyUAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'LazyUBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'LazyUButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'LazyUButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'LazyUCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'LazyUChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'LazyUDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'LazyUIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'LazyUKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'LazyULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'LazyUMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'LazyUMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'LazyUProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'LazyUCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'LazyUForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'LazyUFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'LazyUInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'LazyUInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'LazyURadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'LazyURadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'LazyURange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'LazyUSelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'LazyUSelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'LazyUTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'LazyUToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'LazyUTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'LazyUCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'LazyUContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'LazyUDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'LazyUSkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'LazyUBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'LazyUCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'LazyUCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'LazyUHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'LazyUPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'LazyUTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'LazyUVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'LazyUContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'LazyUModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'LazyUNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'LazyUNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'LazyUPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'LazyUSlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'LazyUTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'LazyNuxtTurnstile': typeof import("../node_modules/@nuxtjs/turnstile/dist/runtime/components/NuxtTurnstile.vue")['default']
    'LazyUnoIcon': typeof import("../node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyTiptapEditorContent': typeof import("@tiptap/vue-3")['EditorContent']
    'LazyTiptapFloatingMenu': typeof import("@tiptap/vue-3")['FloatingMenu']
    'LazyTiptapBubbleMenu': typeof import("@tiptap/vue-3")['BubbleMenu']
    'LazyVDatePicker': typeof import("v-calendar")['DatePicker']
    'LazyVCalendar': typeof import("v-calendar")['Calendar']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AsideMenu: typeof import("../src/components/AsideMenu.vue")['default']
export const AsideMenuItem: typeof import("../src/components/AsideMenuItem.vue")['default']
export const AsideMenuLayer: typeof import("../src/components/AsideMenuLayer.vue")['default']
export const AsideMenuList: typeof import("../src/components/AsideMenuList.vue")['default']
export const BaseDivider: typeof import("../src/components/BaseDivider.vue")['default']
export const BaseIcon: typeof import("../src/components/BaseIcon.vue")['default']
export const BaseLevel: typeof import("../src/components/BaseLevel.vue")['default']
export const CardBox: typeof import("../src/components/CardBox.vue")['default']
export const CardBoxComponentBody: typeof import("../src/components/CardBoxComponentBody.vue")['default']
export const CardBoxComponentFooter: typeof import("../src/components/CardBoxComponentFooter.vue")['default']
export const CardBoxMenu: typeof import("../src/components/CardBoxMenu.vue")['default']
export const CardBoxMenuMaterial: typeof import("../src/components/CardBoxMenuMaterial.vue")['default']
export const FooterBar: typeof import("../src/components/FooterBar.vue")['default']
export const FormsAdmisiDataDiriMhs: typeof import("../src/components/Forms/Admisi/DataDiriMhs.vue")['default']
export const FormsAdmisiDataOrangTuaWali: typeof import("../src/components/Forms/Admisi/DataOrangTuaWali.vue")['default']
export const FormsAdmisiInformasiKontak: typeof import("../src/components/Forms/Admisi/InformasiKontak.vue")['default']
export const FormsAdmisiPendataanDifabel: typeof import("../src/components/Forms/Admisi/PendataanDifabel.vue")['default']
export const FormsAdmisiPersonalInformation: typeof import("../src/components/Forms/Admisi/PersonalInformation.vue")['default']
export const FormsAdmisiRiwayatPendidikan: typeof import("../src/components/Forms/Admisi/RiwayatPendidikan.vue")['default']
export const FormsAdmisiUnggahBerkas: typeof import("../src/components/Forms/Admisi/UnggahBerkas.vue")['default']
export const FormsAdmisiUploadFiles: typeof import("../src/components/Forms/Admisi/UploadFiles.vue")['default']
export const ModalHistoyApproval: typeof import("../src/components/Modal/HistoyApproval.vue")['default']
export const ModalLoginAsMhs: typeof import("../src/components/Modal/LoginAsMhs.vue")['default']
export const ModalLoginAsPengembang: typeof import("../src/components/Modal/LoginAsPengembang.vue")['default']
export const ModalUploadFileTtd: typeof import("../src/components/Modal/ModalUploadFileTtd.vue")['default']
export const ModalProsesValidasiDitolak: typeof import("../src/components/Modal/ProsesValidasi/Ditolak.vue")['default']
export const ModalProsesValidasiSubmit: typeof import("../src/components/Modal/ProsesValidasi/Submit.vue")['default']
export const ModalUbahPassword: typeof import("../src/components/Modal/UbahPassword.vue")['default']
export const ModalUbahRole: typeof import("../src/components/Modal/UbahRole.vue")['default']
export const ModalUploadSertifikat: typeof import("../src/components/Modal/UploadSertifikat.vue")['default']
export const NavBar: typeof import("../src/components/NavBar.vue")['default']
export const NavBarItem: typeof import("../src/components/NavBarItem.vue")['default']
export const NavBarItemPlain: typeof import("../src/components/NavBarItemPlain.vue")['default']
export const NavBarMenuList: typeof import("../src/components/NavBarMenuList.vue")['default']
export const OverlayLayer: typeof import("../src/components/OverlayLayer.vue")['default']
export const SectionFullScreen: typeof import("../src/components/SectionFullScreen.vue")['default']
export const SectionMain: typeof import("../src/components/SectionMain.vue")['default']
export const SelectCustom: typeof import("../src/components/Select_custom.vue")['default']
export const TableDataTable: typeof import("../src/components/Table/DataTable.vue")['default']
export const TableTabulator: typeof import("../src/components/TableTabulator.vue")['default']
export const UserAvatar: typeof import("../src/components/UserAvatar.vue")['default']
export const UserAvatarCurrentUser: typeof import("../src/components/UserAvatarCurrentUser.vue")['default']
export const UtilsFormsCKEditor: typeof import("../src/components/Utils/Forms/CKEditor.vue")['default']
export const UtilsFormsCKEditor2: typeof import("../src/components/Utils/Forms/CKEditor2.vue")['default']
export const UtilsFormsDatePicker: typeof import("../src/components/Utils/Forms/DatePicker.vue")['default']
export const UtilsFormsQuillEditor: typeof import("../src/components/Utils/Forms/QuillEditor.vue")['default']
export const UtilsFormsTextEditor: typeof import("../src/components/Utils/Forms/TextEditor.vue")['default']
export const UtilsFormsTextEditorTipTap: typeof import("../src/components/Utils/Forms/TextEditorTipTap.vue")['default']
export const UtilsFormsTinyMCE: typeof import("../src/components/Utils/Forms/TinyMCE.vue")['default']
export const UtilsSkeletonsQalender: typeof import("../src/components/Utils/Skeletons/Qalender.vue")['default']
export const UAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const UAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const UAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const UAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const UBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const UButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const UButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const UCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const UChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const UDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const UIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const UKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const ULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const UMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const UMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const UProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const UCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const UForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const UFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const UInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const UInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const URadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const URadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const URange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const USelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const USelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const UTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const UToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const UTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const UCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const UContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const UDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const USkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const UBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const UCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const UCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const UHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const UPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const UTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const UVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const UContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const UModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const UNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const UNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const UPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const USlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const UTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const NuxtTurnstile: typeof import("../node_modules/@nuxtjs/turnstile/dist/runtime/components/NuxtTurnstile.vue")['default']
export const UnoIcon: typeof import("../node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const TiptapEditorContent: typeof import("@tiptap/vue-3")['EditorContent']
export const TiptapFloatingMenu: typeof import("@tiptap/vue-3")['FloatingMenu']
export const TiptapBubbleMenu: typeof import("@tiptap/vue-3")['BubbleMenu']
export const VDatePicker: typeof import("v-calendar")['DatePicker']
export const VCalendar: typeof import("v-calendar")['Calendar']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAsideMenu: typeof import("../src/components/AsideMenu.vue")['default']
export const LazyAsideMenuItem: typeof import("../src/components/AsideMenuItem.vue")['default']
export const LazyAsideMenuLayer: typeof import("../src/components/AsideMenuLayer.vue")['default']
export const LazyAsideMenuList: typeof import("../src/components/AsideMenuList.vue")['default']
export const LazyBaseDivider: typeof import("../src/components/BaseDivider.vue")['default']
export const LazyBaseIcon: typeof import("../src/components/BaseIcon.vue")['default']
export const LazyBaseLevel: typeof import("../src/components/BaseLevel.vue")['default']
export const LazyCardBox: typeof import("../src/components/CardBox.vue")['default']
export const LazyCardBoxComponentBody: typeof import("../src/components/CardBoxComponentBody.vue")['default']
export const LazyCardBoxComponentFooter: typeof import("../src/components/CardBoxComponentFooter.vue")['default']
export const LazyCardBoxMenu: typeof import("../src/components/CardBoxMenu.vue")['default']
export const LazyCardBoxMenuMaterial: typeof import("../src/components/CardBoxMenuMaterial.vue")['default']
export const LazyFooterBar: typeof import("../src/components/FooterBar.vue")['default']
export const LazyFormsAdmisiDataDiriMhs: typeof import("../src/components/Forms/Admisi/DataDiriMhs.vue")['default']
export const LazyFormsAdmisiDataOrangTuaWali: typeof import("../src/components/Forms/Admisi/DataOrangTuaWali.vue")['default']
export const LazyFormsAdmisiInformasiKontak: typeof import("../src/components/Forms/Admisi/InformasiKontak.vue")['default']
export const LazyFormsAdmisiPendataanDifabel: typeof import("../src/components/Forms/Admisi/PendataanDifabel.vue")['default']
export const LazyFormsAdmisiPersonalInformation: typeof import("../src/components/Forms/Admisi/PersonalInformation.vue")['default']
export const LazyFormsAdmisiRiwayatPendidikan: typeof import("../src/components/Forms/Admisi/RiwayatPendidikan.vue")['default']
export const LazyFormsAdmisiUnggahBerkas: typeof import("../src/components/Forms/Admisi/UnggahBerkas.vue")['default']
export const LazyFormsAdmisiUploadFiles: typeof import("../src/components/Forms/Admisi/UploadFiles.vue")['default']
export const LazyModalHistoyApproval: typeof import("../src/components/Modal/HistoyApproval.vue")['default']
export const LazyModalLoginAsMhs: typeof import("../src/components/Modal/LoginAsMhs.vue")['default']
export const LazyModalLoginAsPengembang: typeof import("../src/components/Modal/LoginAsPengembang.vue")['default']
export const LazyModalUploadFileTtd: typeof import("../src/components/Modal/ModalUploadFileTtd.vue")['default']
export const LazyModalProsesValidasiDitolak: typeof import("../src/components/Modal/ProsesValidasi/Ditolak.vue")['default']
export const LazyModalProsesValidasiSubmit: typeof import("../src/components/Modal/ProsesValidasi/Submit.vue")['default']
export const LazyModalUbahPassword: typeof import("../src/components/Modal/UbahPassword.vue")['default']
export const LazyModalUbahRole: typeof import("../src/components/Modal/UbahRole.vue")['default']
export const LazyModalUploadSertifikat: typeof import("../src/components/Modal/UploadSertifikat.vue")['default']
export const LazyNavBar: typeof import("../src/components/NavBar.vue")['default']
export const LazyNavBarItem: typeof import("../src/components/NavBarItem.vue")['default']
export const LazyNavBarItemPlain: typeof import("../src/components/NavBarItemPlain.vue")['default']
export const LazyNavBarMenuList: typeof import("../src/components/NavBarMenuList.vue")['default']
export const LazyOverlayLayer: typeof import("../src/components/OverlayLayer.vue")['default']
export const LazySectionFullScreen: typeof import("../src/components/SectionFullScreen.vue")['default']
export const LazySectionMain: typeof import("../src/components/SectionMain.vue")['default']
export const LazySelectCustom: typeof import("../src/components/Select_custom.vue")['default']
export const LazyTableDataTable: typeof import("../src/components/Table/DataTable.vue")['default']
export const LazyTableTabulator: typeof import("../src/components/TableTabulator.vue")['default']
export const LazyUserAvatar: typeof import("../src/components/UserAvatar.vue")['default']
export const LazyUserAvatarCurrentUser: typeof import("../src/components/UserAvatarCurrentUser.vue")['default']
export const LazyUtilsFormsCKEditor: typeof import("../src/components/Utils/Forms/CKEditor.vue")['default']
export const LazyUtilsFormsCKEditor2: typeof import("../src/components/Utils/Forms/CKEditor2.vue")['default']
export const LazyUtilsFormsDatePicker: typeof import("../src/components/Utils/Forms/DatePicker.vue")['default']
export const LazyUtilsFormsQuillEditor: typeof import("../src/components/Utils/Forms/QuillEditor.vue")['default']
export const LazyUtilsFormsTextEditor: typeof import("../src/components/Utils/Forms/TextEditor.vue")['default']
export const LazyUtilsFormsTextEditorTipTap: typeof import("../src/components/Utils/Forms/TextEditorTipTap.vue")['default']
export const LazyUtilsFormsTinyMCE: typeof import("../src/components/Utils/Forms/TinyMCE.vue")['default']
export const LazyUtilsSkeletonsQalender: typeof import("../src/components/Utils/Skeletons/Qalender.vue")['default']
export const LazyUAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const LazyUAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const LazyUAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const LazyUAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const LazyUBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const LazyUButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const LazyUButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const LazyUCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const LazyUChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const LazyUDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const LazyUIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const LazyUKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const LazyULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const LazyUMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const LazyUMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const LazyUProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const LazyUCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const LazyUForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const LazyUFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const LazyUInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const LazyUInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const LazyURadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const LazyURadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const LazyURange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const LazyUSelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const LazyUSelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const LazyUTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const LazyUToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const LazyUTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const LazyUCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const LazyUContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const LazyUDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const LazyUSkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const LazyUBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const LazyUCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const LazyUCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const LazyUHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const LazyUPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const LazyUTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const LazyUVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const LazyUContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const LazyUModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const LazyUNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const LazyUNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const LazyUPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const LazyUSlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const LazyUTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const LazyNuxtTurnstile: typeof import("../node_modules/@nuxtjs/turnstile/dist/runtime/components/NuxtTurnstile.vue")['default']
export const LazyUnoIcon: typeof import("../node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyTiptapEditorContent: typeof import("@tiptap/vue-3")['EditorContent']
export const LazyTiptapFloatingMenu: typeof import("@tiptap/vue-3")['FloatingMenu']
export const LazyTiptapBubbleMenu: typeof import("@tiptap/vue-3")['BubbleMenu']
export const LazyVDatePicker: typeof import("v-calendar")['DatePicker']
export const LazyVCalendar: typeof import("v-calendar")['Calendar']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
